import { v4 as uuidv4 } from 'uuid';
export const sideNavbarLinks = [
  {
    imgSrc: "/assets/icons/home.svg",
    label: "Home",
  },
  {
    imgSrc: "/assets/icons/volume.svg",
    label: "Campaign",
  },
  {
    imgSrc: "/assets/icons/bag.svg",
    label: "Products",
  },
  {
    imgSrc: "/assets/icons/user.svg",
    label: "Customers",
  },
];

export const staticData = [
  {
    id: uuidv4(),
    productImg: "/assets/icons/bluberry-cake-with-raw-toppings.png",
    productName: "Bluberry cake with raw toppings",
    productPrice: "Rs:2,290",
    dateCreated: "01-11-2023",
    campaignTimeline: "Daily",
    campaignStartDate: "2023-01-11",
    campaignEndDate: "2023-02-11",
    clicks: Math.floor(Math.random() * (800 - 200 + 1)) + 200,
    budget: "INR.20,000",
    targetRadius: 17,
    location: "Madurai",
    platform: "google",
    status: "Live now",
  },
  {
    id: uuidv4(),
    productImg: "/assets/icons/chocolate-truffle-cake.png",
    productName: "Chocolate truffle cake",
    productPrice: "Rs:2,190",
    dateCreated: "03-01-2023",
    campaignTimeline: "Lifetime",
    campaignStartDate: "2023-03-01",
    campaignEndDate: "2023-05-01",
    clicks: Math.floor(Math.random() * (800 - 200 + 1)) + 200,
    budget: "INR.40,000",
    targetRadius: 19,
    location: "Trichy",
    platform: "youtube",
    status: "Live now",
  },
  {
    id: uuidv4(),
    productImg: "/assets/icons/browine-cake-with-fluffy-cream.png",
    productName: "Browine cake with fluffy cream",
    productPrice: "Rs:1,222",
    dateCreated: "02-21-2023",
    campaignTimeline: "Daily",
    campaignStartDate: "2023-02-21",
    campaignEndDate: "2023-05-21",
    clicks: Math.floor(Math.random() * (800 - 200 + 1)) + 200,
    budget: "INR.70,000",
    targetRadius: 7,
    location: "Tuticorin",
    platform: "fb",
    status: "Paused",
  },
  {
    id: uuidv4(),
    productImg: "/assets/icons/ferro-rocher-cake.png",
    productName: "Ferro rocher cake",
    productPrice: "RS:1,234",
    dateCreated: "04-24-2023",
    campaignTimeline: "Lifetime",
    campaignStartDate: "2023-04-24",
    campaignEndDate: "2023-05-24",
    clicks: Math.floor(Math.random() * (800 - 200 + 1)) + 200,
    budget: "INR.15,000",
    targetRadius: 5,
    location: "Virudhunagar",
    platform: "instagram",
    status: "Exhausted",
  },
  {
    id: uuidv4(),
    productImg: "/assets/icons/custurd-mixed-with-fruit-cake.png",
    productName: "Custurd mixed with fruit cake",
    productPrice: "Rs:2,456",
    dateCreated: "05-27-2023",
    campaignTimeline: "Daily",
    campaignStartDate: "2023-05-27",
    campaignEndDate: "2023-06-27",
    clicks: Math.floor(Math.random() * (800 - 200 + 1)) + 200,
    budget: "INR.15,000",
    targetRadius: 11,
    location: "Ramnad",
    platform: "google",
    status: "Live now",
  },
  {
    id: uuidv4(),
    productImg: "/assets/icons/best-raw-topping-choco-cake.png",
    productName: "Best raw topping choco cake",
    productPrice: "Rs:2,345",
    dateCreated: "06-15-2023",
    campaignTimeline: "Daily",
    campaignStartDate: "2023-06-15",
    campaignEndDate: "2023-07-15",
    clicks: Math.floor(Math.random() * (800 - 200 + 1)) + 200,
    budget: "INR.18,000",
    targetRadius: 29,
    location: "Kanyakumari",
    platform: "youtube",
    status: "Paused",
  },
  {
    id: uuidv4(),
    productImg: "/assets/icons/green-cup-cakes.png",
    productName: "Green cup cakes",
    productPrice: "Rs:1,234",
    dateCreated: "07-09-2023",
    campaignTimeline: "Lifetime",
    campaignStartDate: "2023-07-09",
    campaignEndDate: "2023-08-09",
    clicks: Math.floor(Math.random() * (800 - 200 + 1)) + 200,
    budget: "INR.11,000",
    targetRadius: 12,
    location: "Pondicherry",
    platform: "instagram",
    status: "Live now",
  },
  {
    id: uuidv4(),
    productImg: "/assets/icons/blueberry-topping-cakes.png",
    productName: "Blueberry topping cakes",
    productPrice: "Rs:2,456",
    dateCreated: "08-07-2023",
    campaignTimeline: "Daily",
    campaignStartDate: "2023-08-07",
    campaignEndDate: "2023-10-07",
    clicks: Math.floor(Math.random() * (800 - 200 + 1)) + 200,
    budget: "INR.35,000",
    targetRadius: 24,
    location: "Salem",
    platform: "youtube",
    status: "Paused",
  },
  {
    id: uuidv4(),
    productImg: "/assets/icons/strawberry-cakes-with-blueberry.png",
    productName: "Strawberry cakes with blueberry",
    productPrice: "Rs:2,345",
    dateCreated: "09-19-2023",
    campaignTimeline: "Lifetime",
    campaignStartDate: "2023-09-19",
    campaignEndDate: "2023-10-19",
    clicks: Math.floor(Math.random() * (800 - 200 + 1)) + 200,
    budget: "INR.17,000",
    targetRadius: 27,
    location: "Chennai",
    platform: "fb",
    status: "Live now",
  }
]

export const steps = [
  {
    icon: "/assets/icons/lamp-charge.svg",
    alt: "lamp charge",
    label: "What you want to do",
  },
  {
    icon: "/assets/icons/progress-bag.svg",
    alt: "bag",
    label: "Choose product",
  },
  {
    icon: "/assets/icons/appointments.svg",
    alt: "appointments",
    label: "Campaign settings",
  },
  {
    icon: "/assets/icons/progress-tick-circle.svg",
    alt: "tick circle",
    label: "Ready to go",
  },
];

export const campaignTypes = [
  {
    id: 1,
    icon: "/assets/icons/phonecall-receive.svg",
    iconAlt: "phonecall recieve",
    title: "Get Leads as calls",
    description: "Reach broad audience and get leads through calls",
    platform: "google",
  },
  {
    id: 2,
    icon: "/assets/icons/inbox.svg",
    iconAlt: "inbox",
    title: "Get Leads as Facebook messages",
    description: "Get more FB messages from Leads",
    platform: "fb",
  },
  {
    id: 3,
    icon: "/assets/icons/add-user.svg",
    iconAlt: "add user",
    title: "Increase page followers",
    description: "Encourage customers to follow your page",
    platform: "fb",
  },
  {
    id: 4,
    icon: "/assets/icons/users.svg",
    iconAlt: "users",
    title: "Get Customer Leads",
    description: "Encourage customers to take action",
    platform: "fb",
  },
  {
    id: 5,
    icon: "/assets/icons/eye.svg",
    iconAlt: "eye",
    title: "Get more youtube views",
    description: "Increase organic views by obtaining user attention ",
    platform: "youtube",
  },
  {
    id: 6,
    icon: "/assets/icons/arrow.svg",
    iconAlt: "arrow",
    title: "Get more website traffic",
    description: "Get the right people to visit your website",
    platform: "instagram",
  },
  {
    id: 7,
    icon: "/assets/icons/store.svg",
    iconAlt: "store",
    title: "Increase Live store traffic",
    description: "Drive visits to local stores, restaurants & Dealerships",
    platform: "google",
  },
  {
    id: 8,
    icon: "/assets/icons/install.svg",
    iconAlt: "install",
    title: "Increase your App installs",
    description: "Get more installs, interactions for your app",
    platform: "youtube",
  },
  {
    id: 9,
    icon: "/assets/icons/clipboard.svg",
    iconAlt: "clipboard",
    title: "Increase the catalogue sales",
    description: "Drive the sales of your catalogue and get more leads",
    platform: "google",
  },
];

export const productTypes = [
  {
    id: 1,
    icon: "/assets/icons/bluberry-cake-with-raw-toppings.png",
    iconAlt: "Bluberry cake with raw toppings",
    productName: "Bluberry cake with raw toppings",
    price: "Rs:2,290",
  },
  {
    id: 2,
    icon: "/assets/icons/chocolate-truffle-cake.png",
    iconAlt: "Chocolate truffle cake",
    productName: "Chocolate truffle cake",
    price: "Rs:2,190",
  },
  {
    id: 3,
    icon: "/assets/icons/browine-cake-with-fluffy-cream.png",
    iconAlt: "Browine cake with fluffy cream",
    productName: "Browine cake with fluffy cream",
    price: "Rs:1,222",
  },
  {
    id: 4,
    icon: "/assets/icons/ferro-rocher-cake.png",
    iconAlt: "Ferro rocher cake",
    productName: "Ferro rocher cake",
    price: "RS:1,234",
  },
  {
    id: 5,
    icon: "/assets/icons/custurd-mixed-with-fruit-cake.png",
    iconAlt: "Custurd mixed with fruit cake",
    productName: "Custurd mixed with fruit cake",
    price: "Rs:2,456",
  },
  {
    id: 6,
    icon: "/assets/icons/best-raw-topping-choco-cake.png",
    iconAlt: "Best raw topping choco cake",
    productName: "Best raw topping choco cake",
    price: "Rs:2,345",
  },
  {
    id: 7,
    icon: "/assets/icons/green-cup-cakes.png",
    iconAlt: "Green cup cakes",
    productName: "Green cup cakes",
    price: "Rs:1,234",
  },
  {
    id: 8,
    icon: "/assets/icons/blueberry-topping-cakes.png",
    iconAlt: "Blueberry topping cakes",
    productName: "Blueberry topping cakes",
    price: "Rs:2,456",
  },
  {
    id: 9,
    icon: "/assets/icons/strawberry-cakes-with-blueberry.png",
    iconAlt: "Strawberry cakes with blueberry",
    productName: "Strawberry cakes with blueberry",
    price: "Rs:2,345",
  },
];

export const cities = [
  "Chennai",
  "	Coimbatore",
  "Madurai",
  "Tiruchirappalli",
  "Tiruppur",
  "Salem",
  "Erode",
  "Tirunelveli",
  "Thoothukkudi",
  "Nagercoil",
  "Thanjavur",
  "Dindigul",
  "Kanchipuram",
  "Tiruvannamalai",
  "Kumbakonam",
  "Rajapalayam",
  "Virudhunagar",
  "Pudukottai",
  "Hosur",
  "Krishnagiri",
  "Ambur",
  "Vellore",
  "Karaikkudi",
  "Sivaganga",
  "Neyveli",
  "Cuddalore",
  "Nagapattinam",
];

export const previewImages = [
  {
    id: 1,
    imgSrc: "/assets/images/cake-1.png",
  },
  {
    id: 2,
    imgSrc: "/assets/images/cake-2.png",
  },
  {
    id: 3,
    imgSrc: "/assets/images/cake-3.png",
  },
  {
    id: 4,
    imgSrc: "/assets/images/cake-4.png",
  },
];
